### PR TITLE
fixed some url, was moved, in readme.md

### PR DESCRIPTION
**Pull request by ianchen0119**
Signed-off-by: Ian Chen <iancodinghtml@gmail.com>

### CODE REVIEW

**Comment by mbwhite** [comment]
Hello thanks for the PR; can you remove the version number updates please. We only update those when we do a release.

**Comment by ianchen0119** [comment]
Thanks for your comment, I will revise this tomorrow.

**Comment by ianchen0119** [comment]
> Hello thanks for the PR; can you remove the version number updates please. We only update those when we do a release.

Dear mbwhite,
I have checked about you mentioned above.
But I haven't changed any content about package.json.
In this commit, I revise the bad url in fabric-shim/README.md only.
If it be possible, could you tell me what causes about version number have been changed?
Thanks a lot.

**Comment by mbwhite** [comment]
@ianchen0119 Hello - can you check you pushed the commits please?  
The changes in the PR seem to be unchanged. 

The versions numbers are updated when we do a release.

**Comment by ianchen0119** [comment]
@mbwhite I have revised any file about problem of version number, thanks.

**Comment by mbwhite** [comment]
Thanks - the build looks like it's failing for an npm audit issue... trying to fix that in https://github.com/hyperledger/fabric-chaincode-node/pull/156

**Pull request merged**
