### PR TITLE
Rename the root json config file

### PR DESCRIPTION
**Pull request by mbwhite**
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

### CODE REVIEW

**Review by jt-nti — COMMENTED** [review]
Is anything else from this file still used? If not, could the version come from one of the real package.json files instead so this file can just get deleted?

**Comment by mbwhite** [comment]
I think that's quite reasonable @jt-nti and in theory should work.. though as the Azure Pipeline is... err.... completely broken at present.

**Comment by jt-nti** [comment]
@mbwhite whether the file is renamed or deleted, don't forget to update [RELEASING.md](https://github.com/hyperledger/fabric-chaincode-node/blob/main/RELEASING.md)!

**Comment by mbwhite** [comment]
> @mbwhite whether the file is renamed or deleted, don't forget to update [RELEASING.md](https://github.com/hyperledger/fabric-chaincode-node/blob/main/RELEASING.md)!

good reminder thanks.

**Review by jt-nti — APPROVED** [review]

**Pull request merged**
