### PR TITLE
Fix: ChaincodeStub.getMspID should be in lowerCamelCASE

### PR DESCRIPTION
**Pull request by winderica**

### CODE REVIEW

**Comment by winderica** [comment]
Just a suggestion, it's a bit confusing between `(ClientIdentity.)getMSPID` and `(ChaincodeStub.)getMspID`, could we unify their cases for consistency?

**Comment by jt-nti** [comment]
It would definitely be nice to be consistent but need to make sure a change to ClientIdentity doesn't break anyone

**Comment by winderica** [comment]
IMHO, we can support both of them for a period of time, and show a warning message when the deprecated one is called.

**Comment by jt-nti** [comment]
@winderica that sounds sensible to me. Please could you create an issue on the chaincode node Jira project for that https://jira.hyperledger.org/projects/FABCN/issues/FABCN-125?filter=allopenissues

**Comment by winderica** [comment]
[Done](https://jira.hyperledger.org/browse/FABCN-423). 😊

**Pull request merged**
