### PR TITLE
Fix the handling of the key endorsement policy

### PR DESCRIPTION
**Pull request by mbwhite**
The nOutOf was missing.

'specifically' this line wasn't there before... 

```
policy.setNOutOf(nOutOf);
```

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

### CODE REVIEW

**Comment by mbwhite** [comment]
Note - I've raised #378 to bring over better testing.  The last two issues haven't been properly caught in the existing fv tests.

**Comment by mbwhite** [comment]
@mergify port main

**Comment by mbwhite** [comment]
> Sorry but I didn't understand the command. Please consult [the commands documentation](https://docs.mergify.com/commands.html) 📚.

just can't get the quality AIs these days...

**Comment by mbwhite** [comment]
resolves #377

**Comment by jkneubuh** [comment]
I have tested these updates with a local build / tgz, and confirmed they fix the current build error running the FSAT tests with 2.5.1.   Thank you @mbwhite for the fix.

**Pull request merged**
