### PR TITLE
Fixing the "Working with iterators" documentation

### PR DESCRIPTION
**Pull request by rajat-dlt**
Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>

### CODE REVIEW

**Comment by rajat-dlt** [comment]
@mbwhite, could you help me with this ? 
Do I require to make to make any further changes in the files ?

**Comment by mbwhite** [comment]
Thanks great thank you @rajat-dlt

**Review by mbwhite — APPROVED** [review]

**Comment by mbwhite** [comment]
@mergifyio backport release-2.2

**Comment by davidkel** [comment]
@Mergifyio backport release-2.2

**Comment by davidkel** [comment]
https://github.com/Mergifyio backport release-2.2

**Pull request merged**
